"use client";
import {useEffect,useMemo,useState} from "react";

type TF="1h"|"4h"; type Coin="BTCUSDT"|"ETHUSDT"|"SOLUSDT";
type Candle={t:number,o:number,h:number,l:number,c:number,v:number};
type Analysis={price:number,change:number,rsi:number,ema20:number,ema50:number,atr:number,support:number,resistance:number,volume:number,avgVolume:number,trend:string,signal:string,score:number,breakout:string,candles:Candle[]};
const COINS:Coin[]=["BTCUSDT","ETHUSDT","SOLUSDT"];
const names:Record<Coin,string>={BTCUSDT:"Bitcoin",ETHUSDT:"Ethereum",SOLUSDT:"Solana"};
function ema(a:number[],p:number){const k=2/(p+1);let e=a[0]||0;for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a:number[],p=14){if(a.length<p+1)return 50;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];d>=0?g+=d:l-=d}let ag=g/p,al=l/p;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}return al===0?100:100-100/(1+ag/al)}
function atr(cs:Candle[],p=14){if(cs.length<p+1)return 0;const tr=cs.slice(1).map((x,i)=>Math.max(x.h-x.l,Math.abs(x.h-cs[i].c),Math.abs(x.l-cs[i].c)));return tr.slice(-p).reduce((a,b)=>a+b,0)/p}
function analyze(cs:Candle[]):Analysis{const closes=cs.map(x=>x.c), last=cs.at(-1)!, prev=cs.at(-2)!;const e20=ema(closes.slice(-80),20),e50=ema(closes.slice(-120),50),r=rsi(closes),a=atr(cs);const recent=cs.slice(-48),support=Math.min(...recent.map(x=>x.l)),resistance=Math.max(...recent.map(x=>x.h));const av=recent.slice(-20).reduce((s,x)=>s+x.v,0)/20;let score=50;score+=e20>e50?14:-14;score+=last.c>e20?10:-10;score+=(r-50)*.35;score+=last.v>av?5:-2;score=Math.max(1,Math.min(99,Math.round(score)));const trend=score>=65?"Bullish":score<=35?"Bearish":"Neutral";const signal=score>=72?"LONG":score<=28?"SHORT":"WAIT";const breakout=last.c>resistance*0.998?"Near/above resistance":last.c<support*1.002?"Near/under support":"Inside range";return {price:last.c,change:(last.c/prev.c-1)*100,rsi:r,ema20:e20,ema50:e50,atr:a,support,resistance,volume:last.v,avgVolume:av,trend,signal,score,breakout,candles:cs}}
async function getData(symbol:Coin,tf:TF){const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${tf}&limit=150`);if(!r.ok)throw new Error("Market data unavailable");const d=await r.json();return d.map((x:any)=>({t:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]})) as Candle[]}
function fmt(n:number){return n>=1000?n.toLocaleString(undefined,{maximumFractionDigits:0}):n.toLocaleString(undefined,{maximumFractionDigits:4})}
function MiniChart({c}:{c:Candle[]}){const w=720,h=190,p=8,lo=Math.min(...c.map(x=>x.l)),hi=Math.max(...c.map(x=>x.h));const pts=c.map((x,i)=>`${p+i*(w-2*p)/(c.length-1)},${h-p-(x.c-lo)/(hi-lo||1)*(h-2*p)}`).join(" ");return <svg viewBox={`0 0 ${w} ${h}`} className="chart"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="2"/></svg>}
function Card({coin,tf,a}:{coin:Coin,tf:TF,a:Analysis}){return <section className="card"><div className="cardhead"><div><b>{names[coin]}</b><span>{coin.replace("USDT","/USDT")} · {tf.toUpperCase()}</span></div><div className={a.change>=0?"up":"down"}>{a.change>=0?"+":""}{a.change.toFixed(2)}%</div></div><div className="price">{fmt(a.price)}</div><MiniChart c={a.candles.slice(-60)}/><div className="grid"><Metric k="RSI(14)" v={a.rsi.toFixed(1)} tone={a.rsi>70?"hot":a.rsi<30?"good":""}/><Metric k="EMA 20" v={fmt(a.ema20)}/><Metric k="EMA 50" v={fmt(a.ema50)}/><Metric k="ATR" v={fmt(a.atr)}/><Metric k="Support" v={fmt(a.support)}/><Metric k="Resistance" v={fmt(a.resistance)}/><Metric k="Volume" v={fmt(a.volume)}/><Metric k="Avg Vol" v={fmt(a.avgVolume)}/></div><div className="signalrow"><span className={a.trend.toLowerCase()}>{a.trend}</span><strong>{a.signal}</strong><span>Score {a.score}%</span></div><div className="bar"><i style={{width:`${a.score}%`}}/></div><small>{a.breakout} · educational analysis, not financial advice.</small></section>}
function Metric({k,v,tone=""}:{k:string,v:string,tone?:string}){return <div className="metric"><span>{k}</span><b className={tone}>{v}</b></div>}
export default function Home(){const [tf,setTf]=useState<TF>("1h"),[data,setData]=useState<Partial<Record<Coin,Analysis>>>({}),[loading,setLoading]=useState(true),[err,setErr]=useState("");async function load(){setLoading(true);setErr("");try{const xs=await Promise.all(COINS.map(async c=>[c,analyze(await getData(c,tf))] as const));setData(Object.fromEntries(xs));}catch(e){setErr(e instanceof Error?e.message:"Unable to load market data")}finally{setLoading(false)}}useEffect(()=>{load();const id=setInterval(load,60000);return()=>clearInterval(id)},[tf]);const avg=useMemo(()=>{const x=COINS.map(c=>data[c]?.score).filter((x):x is number=>x!==undefined);return x.length?Math.round(x.reduce((a,b)=>a+b,0)/x.length):0},[data]);return <main><header><div><div className="eyebrow">FREE CRYPTO INTELLIGENCE</div><h1>Crypto Analysis <span>Pro</span></h1><p>BTC · ETH · SOL | live market structure, momentum & risk levels</p></div><div className="controls"><button className={tf==="1h"?"active":""} onClick={()=>setTf("1h")}>1H</button><button className={tf==="4h"?"active":""} onClick={()=>setTf("4h")}>4H</button><button onClick={load}>↻ Refresh</button></div></header><div className="summary"><div><span>Market bias</span><b>{avg>=65?"Bullish":avg<=35?"Bearish":"Mixed"}</b></div><div><span>Composite score</span><b>{avg || "—"}%</b></div><div><span>Data</span><b>Binance public API</b></div><div><span>Refresh</span><b>60 sec</b></div></div>{err&&<div className="error">{err}. Binance may be rate-limiting requests; retry shortly.</div>}{loading&&!Object.keys(data).length?<div className="loading">Loading live market structure…</div>:<div className="cards">{COINS.map(c=>data[c]&&<Card key={c} coin={c} tf={tf} a={data[c]!}/>)}</div>}<footer>Crypto Analysis Pro · Free market analytics · No trade execution · Not financial advice</footer></main>}
