"use client";
import {useEffect,useState} from "react";

type TF="15m"|"1h"|"4h"|"1d";
const coins=["BTCUSDT","ETHUSDT","SOLUSDT"] as const;
const tfs:TF[]=["15m","1h","4h","1d"];

function ema(a:number[],p:number){let e=a[0]||0,k=2/(p+1);for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a:number[],p=14){if(a.length<p+1)return 50;let g=0,l=0;for(let i=1;i<=p;i++){let d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/p,al=l/p;for(let i=p+1;i<a.length;i++){let d=a[i]-a[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}return al?100-100/(1+ag/al):100}
async function load(s:string,t:TF){let r=await fetch("https://api.binance.com/api/v3/klines?symbol="+s+"&interval="+t+"&limit=120");if(!r.ok)throw Error("Binance unavailable");let d=await r.json(),c=d.map((x:any)=>({h:+x[2],l:+x[3],c:+x[4],v:+x[5]}));let p=c.at(-1).c,cl=c.map((x:any)=>x.c),e20=ema(cl,20),e50=ema(cl,50),rr=rsi(cl),support=Math.min(...c.slice(-48).map((x:any)=>x.l)),resistance=Math.max(...c.slice(-48).map((x:any)=>x.h)),avg=c.slice(-20).reduce((a:any,x:any)=>a+x.v,0)/20,score=Math.max(1,Math.min(99,Math.round(50+(e20>e50?15:-15)+(p>e20?10:-10)+(rr-50)*.35+(c.at(-1).v>avg?6:-2))));return{p,e20,e50,rr,support,resistance,score,trend:score>=65?"Bullish":score<=35?"Bearish":"Neutral",signal:score>=80?"STRONG LONG":score>=68?"LONG":score<=20?"STRONG SHORT":score<=32?"SHORT":"WAIT"}}
export default function Advanced(){const[tf,setTf]=useState<TF>("1h"),[rows,setRows]=useState<any[]>([]),[err,setErr]=useState("");useEffect(()=>{let on=true;(async()=>{try{let out:any[]=[];for(const s of coins){let a:any={};for(const t of tfs)a[t]=await load(s,t);out.push({s,a})}if(on)setRows(out)}catch(e){if(on)setErr(String(e))}})();return()=>{on=false}},[]);return <main><header><div><div className="eyebrow">ADVANCED ENGINE</div><h1>Multi-Timeframe <span>Confluence</span></h1><p>15m · 1H · 4H · 1D | trend, momentum and structure</p></div><div className="controls">{tfs.map(t=><button key={t} className={tf===t?"active":""} onClick={()=>setTf(t)}>{t.toUpperCase()}</button>)}</div></header>{err&&<div className="error">{err}</div>}<div className="cards">{rows.map(({s,a})=>{let x=a[tf],avg=Math.round(tfs.reduce((n,t)=>n+a[t].score,0)/4),aligned=tfs.filter(t=>a[t].trend===x.trend).length;return <section className="card" key={s}><div className="cardhead"><div><b>{s.replace("USDT","/USDT")}</b><span>{tf.toUpperCase()}</span></div><b className={x.trend.toLowerCase()}>{x.trend}</b></div><div className="price">{x.p.toLocaleString()}</div><div className="grid"><div className="metric"><span>RSI</span><b>{x.rr.toFixed(1)}</b></div><div className="metric"><span>EMA 20 / 50</span><b>{x.e20.toFixed(2)} / {x.e50.toFixed(2)}</b></div><div className="metric"><span>Support</span><b>{x.support.toFixed(2)}</b></div><div className="metric"><span>Resistance</span><b>{x.resistance.toFixed(2)}</b></div></div><div className="signalrow"><strong>{x.signal}</strong><span>Score {x.score}</span></div><div className="bar"><i style={{width:x.score+"%"}}/></div><div className="confluence">MTF score <b>{avg}/99</b> · {aligned}/4 aligned</div><small>Heuristic analysis; backtest before trading.</small></section>})}</div><footer>Advanced view · Free public market data · No trade execution</footer></main>}
